---
name: Docker Build and Deploy
on:
  workflow_call:
    inputs:
      awsRegion:
        required: true
        type: string
    secrets:
      bitbucketSSHKey:
        required: true
      sshKey:
        required: true
      awsAccessKeyId:
        required: true
      awsSecretAccessKey:
        required: true
jobs:
  docker_build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: |
            ${{ secrets.bitbucketSSHKey }}
            ${{ secrets.sshKey }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.5.5
        with:
          aws-access-key-id: ${{ secrets.awsAccessKeyId }}
          aws-secret-access-key: ${{ secrets.awsSecretAccessKey }}
          aws-region: ${{ inputs.awsRegion }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.3.1

      - name: Get current timestamp
        id: timestamp
        run: echo "::set-output name=now::$(date +'%s')"

      - name: Version
        id: version
        run: echo "VERSION=${GITHUB_REF##*/}-${GITHUB_SHA}" >>$GITHUB_ENV

      - name: Docker tags - other than tag ref
        id: docker_meta
        env:
          DOCKER_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          DOCKER_REPOSITORY="${DOCKER_REGISTRY}/${GITHUB_REPOSITORY,,}"
          TAGS="-t ${DOCKER_REPOSITORY}:${VERSION} -t ${DOCKER_REPOSITORY}:${GITHUB_REF##*/}-${{ steps.timestamp.outputs.now }}-${GITHUB_SHA}"
          echo "DOCKER_TAGS=${TAGS}" >>$GITHUB_ENV
        shell: bash
        if: ${{ ! contains(github.ref, '/tags/') }}

      - name: Docker tags - tag ref
        id: tagged_build
        env:
          DOCKER_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          DOCKER_REPOSITORY="${DOCKER_REGISTRY}/${GITHUB_REPOSITORY,,}"
          TAGS="-t ${DOCKER_REPOSITORY}:${VERSION} -t ${DOCKER_REPOSITORY}:${GITHUB_REF##*/}-${{ steps.timestamp.outputs.now }}-${GITHUB_SHA} -t ${DOCKER_REPOSITORY}:${GITHUB_REF##*/}"
          echo "DOCKER_TAGS=${TAGS}" >>$GITHUB_ENV
        shell: bash
        if: ${{ contains(github.ref, '/tags/') }}

      - name: Set docker push
        run: |
          echo "DOCKER_PUSH=--push" >>$GITHUB_ENV
        shell: bash
        if: ${{ github.event_name != 'pull_request' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.0.3

      - name: Build (and push)
        run: |
          docker buildx build --ssh=default=${SSH_AUTH_SOCK} \
            ${DOCKER_TAGS} ${DOCKER_PUSH} \
            --build-arg GITHUB_TOKEN --build-arg VERSION .
