---
name: Deploy Swagger
on:
  workflow_call:
    inputs:
      awsRegion:
        required: true
        type: string
      projectName:
        required: true
        type: string
      swaggerFile:
        required: true
        type: string
    secrets:
      swaggerBucket:
        required: true
      awsAccessKeyId:
        required: true
      awsSecretAccessKey:
        required: true
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.5.5
        with:
          aws-access-key-id: ${{ secrets.awsAccessKeyId }}
          aws-secret-access-key: ${{ secrets.awsSecretAccessKey }}
          aws-region: ${{ inputs.awsRegion }}

      - name: Show File
        run: ls

      - name: Check if Swagger Exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ${{ inputs.swaggerFile }}

      - name: Deploy swagger api to S3 bucket
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          aws s3 cp ${{ inputs.swaggerFile }} "${{ secrets.swaggerS3Bucket }}/${{ inputs.projectName }}/openapi3.json" --acl public-read
